export const homeListData = [
  {
    id: 1,
    name: 'Prisha Mclaughlin',
    time: '52 minutes ago',
    description: 'I Lost My Electric Motor Bike before Todays ago',
    coments: '12 Coments',
    likes: '85 Likes',
    shares: '36 Shared',
    images: require('../Assets/Images/scoter_image.png'),
    profile_image: require('../Assets/Images/dummyman1.png'),
  },
  {
    id: 2,
    name: 'Prisha Mclaughlin',
    time: '52 minutes ago',
    description: 'I Lost My Electric Motor Bike before Todays ago',
    coments: '12 Coments',
    likes: '85 Likes',
    shares: '36 Shared',
    images: require('../Assets/Images/scoter_image.png'),
    profile_image: require('../Assets/Images/dummyman1.png'),
  },
  {
    id: 3,
    name: 'Prisha Mclaughlin',
    time: '52 minutes ago',
    description: 'I Lost My Electric Motor Bike before Todays ago',
    coments: '12 Coments',
    likes: '85 Likes',
    shares: '36 Shared',
    images: require('../Assets/Images/scoter_image.png'),
    profile_image: require('../Assets/Images/dummyman1.png'),
  },
];

export const comentlist = [
  {
    id: 1,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'Prisha Mclaughlin',
    time: '52 minutes ago',
    coment:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    likes: 25,
    replay: '12  replay',
  },
  {
    id: 2,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'Prisha Mclaughlin',
    time: '52 minutes ago',
    coment:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    likes: 25,
    replay: '12  replay',
  },
  {
    id: 3,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'Prisha Mclaughlin',
    time: '52 minutes ago',
    coment:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    likes: 25,
    replay: '12  replay',
  },
];
export const chatlist = [
  {
    id: 1,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'anderson',
    text: 'Hello,Nice to meet you!',
    undread: 2,
  },
  {
    id: 2,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'Lewandowski',
    text: 'thanks for your time.',
    undread: 0,
  },
  {
    id: 3,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'Rodrigo',
    text: 'Send invitation',
    undread: 0,
  },
  {
    id: 4,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'Bambang Ave',
    text: 'yes this is same for...',
    undread: 2,
  },
  {
    id: 5,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'Thomas Partey',
    text: 'okay i waiting for you...',
    undread: 0,
  },
  {
    id: 6,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'Jajang S',
    text: 'yes this is same for...',
    undread: 0,
  },
  {
    id: 7,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'john',
    text: 'thanks for your times',
    undread: 0,
  },
  {
    id: 8,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'Bambang Ave',
    text: 'yes this is same for...',
    undread: 2,
  },
  {
    id: 9,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'Thomas Partey',
    text: 'okay i waiting for you...',
    undread: 0,
  },
  {
    id: 10,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'Jajang S',
    text: 'yes this is same for...',
    undread: 0,
  },
  {
    id: 11,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'john',
    text: 'thanks for your times',
    undread: 0,
  },
];

export const notificationArray = [
  {
    id: 1,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'john',
    text: 'thanks for your times',
  },
  {
    id: 2,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'john',
    text: 'thanks for your times',
  },
  {
    id: 3,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'john',
    text: 'thanks for your times',
  },
  {
    id: 4,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'john',
    text: 'thanks for your times',
  },
  {
    id: 5,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'john',
    text: 'thanks for your times',
  },
  {
    id: 6,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'john',
    text: 'thanks for your times',
  },
  {
    id: 7,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'john',
    text: 'thanks for your times',
  },
  {
    id: 8,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'john',
    text: 'thanks for your times',
  },
  {
    id: 9,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'john',
    text: 'thanks for your times',
  },
  {
    id: 10,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'john',
    text: 'thanks for your times',
  },
  {
    id: 11,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'john',
    text: 'thanks for your times',
  },
  {
    id: 12,
    profile_image: require('../Assets/Images/dummyman1.png'),
    name: 'john',
    text: 'thanks for your times',
  },
];
